name: icon_stack
description: Flutter widget for displaying stacked transformable icons as one icon
version: 1.0.1
repository: https://github.com/aygistov/icon_stack

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
